config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  devise_for :users
  resources :users, :controller => "users"
  resources :branch_office_addresses
  resources :branch_offices
  resources :client_addresses
  resources :clients
  resources :cities
  resources :states
  resources :countries

  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/branch_office.rb
class BranchOffice < ApplicationRecord
  belongs_to :client
  has_many :branch_office_addresses
end

app/models/city.rb
class City < ApplicationRecord
	belongs_to :state
	has_one :client_address
	has_one :branch_office_address
end

app/models/client.rb
class Client < ApplicationRecord
	has_many :client_addresses, :dependent => :destroy
	has_many :branch_offices, :dependent => :destroy


	accepts_nested_attributes_for :client_addresses, :allow_destroy => true


	validates_presence_of :first_name, :last_name, 
		:message => "Este campo es obligatorio."
	validates :dni_number, :cuil_number, 
		numericality: { message: "Se permite solo numeros enteros."}, 
		:allow_nil => true
	#validates_length_of :dni_number, :minimum => 8, :maximum => 8, :message => "Ingrese un DNI válido. (mínimo 8 caracteres numericos, sin puntos ni comas)"
	#validates_length_of :cuil_number, :minimum => 11, :maximum => 11, :message => "Ingrese un CUIL válido. (mínimo 11 caracteres numericos, sin puntos ni comas)"
	validates :email, 
		format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, message: "formato email@email.com"  }, 
		:allow_nil => true

end

app/models/client_address.rb
class ClientAddress < ApplicationRecord
  belongs_to :city
  has_one :state, through: :city
  has_one :country, through: :state
  belongs_to :client

  accepts_nested_attributes_for :city, :state, :country, :allow_destroy => true


end

app/models/country.rb
class Country < ApplicationRecord
	has_many :states
	validates_presence_of :name
end

app/models/state.rb
class State < ApplicationRecord
	belongs_to :country
	has_many :cities
end

app/models/task.rb
class Task < ApplicationRecord
	has_many :user_tasks
	has_many :users, :through => :user_tasks

	#attr_reader :users

	after_create :save_users

	#Custom setter
	def users=(value)
		@users = value
	end

	private

	def save_users
		@users.each do |user_id|
			UserTask.create(user_id: user_id, task_id: self.id)
		end
	end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_tasks
  has_many :tasks, :through => :user_tasks
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :confirmable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :avatar, AvatarUploader
  extend Enumerize
  enumerize :role, in:[:'root', :'admin', :'user'], default: :'user'

end

app/models/user_task.rb
class UserTask < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/controllers/branch_office_addresses_controller.rb
class BranchOfficeAddressesController < ApplicationController
  before_action :set_branch_office_address, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @branch_office_addresses = BranchOfficeAddress.all
    respond_with(@branch_office_addresses)
  end

  def show
    respond_with(@branch_office_address)
  end

  def new
    @branch_office_address = BranchOfficeAddress.new
    respond_with(@branch_office_address)
  end

  def edit
  end

  def create
    @branch_office_address = BranchOfficeAddress.new(branch_office_address_params)
    @branch_office_address.save
    respond_with(@branch_office_address)
  end

  def update
    @branch_office_address.update(branch_office_address_params)
    respond_with(@branch_office_address)
  end

  def destroy
    @branch_office_address.destroy
    respond_with(@branch_office_address)
  end

  private
    def set_branch_office_address
      @branch_office_address = BranchOfficeAddress.find(params[:id])
    end

    def branch_office_address_params
      params.require(:branch_office_address).permit(:street_name, :street_number, :monoblock, :floor, :department_number, :city_id, :branch_office_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @tasks = Task.all
    respond_with(@tasks)
  end

  def show
    respond_with(@task)
  end

  def new
    @task = Task.new
    @users = User.all
    respond_with(@task)
  end

  def edit
  end

  def create
    @task = Task.new(task_params)
    @task.users = params[:users]
    if @task.save
      redirect_to @task
    else
      render :new
    end
    #respond_with(@task)
  end

  def update
    @task.update(task_params)
    respond_with(@task)
  end

  def destroy
    @task.destroy
    respond_with(@task)
  end

  private
    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:title, :description, :users)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# def link_to_remove_fields(name, f)
	# 	f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
	# end

	# def link_to_add_fields(name, f, association)
	# 	new_object = f.object.class.reflect_on_association(association).klass.new
	# 	fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
	#   	render(association.to_s.singularize + "_fields", :f => builder)
	# end
	# 	link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
	# end
	# def link_to_add_fields(name, f, association)  
 #  		new_object = f.object.class.reflect_on_association(association).klass.new  
 #  		fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|  
 #    	render(association.to_s.singularize + "_fields", :f => builder)  
 #  	end  
 #  	link_to name, "#", :onclick => h("add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")"), remote: true
	# end  
end

app/helpers/branch_office_addresses_helper.rb
module BranchOfficeAddressesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
	def link_to_add_fields(name, f, association)
	    new_object = f.object.send(association).klass.new
	    id = new_object.object_id
	    fields = f.fields_for(association, new_object, child_index: id) do |document|
	      render(association.to_s.singularize + "_fields", f: document)
	    end
	    link_to(name, '', class: "add_fields btn btn-success", data: { id: id, fields: fields.gsub("\n", "")})
	end
	def link_to_remove_fields(name, f)
		f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
	end
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/branch_office_addresses/_form.html.erb
<%= form_for(@branch_office_address, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @branch_office_address.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@branch_office_address.errors.count, "error") %> prohibited this branch_office_address from being saved:</h4>

      <ul>
      <% @branch_office_address.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    
      <%= f.label :street_name, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :street_name, class: "form-control" %>
      </div>
    
  </div>
  <div class="form-group">
    
      <%= f.label :street_number, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.number_field :street_number, class: "form-control" %>
      </div>
    
  </div>
  <div class="form-group">
    
      <%= f.label :monoblock, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :monoblock, class: "form-control" %>
      </div>
    
  </div>
  <div class="form-group">
    
      <%= f.label :floor, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :floor, class: "form-control" %>
      </div>
    
  </div>
  <div class="form-group">
    
      <%= f.label :department_number, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.number_field :department_number, class: "form-control" %>
      </div>
    
  </div>
  <div class="form-group">
    
      <%= f.label :city, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :city, class: "form-control" %>
      </div>
    
  </div>
  <div class="form-group">
    
      <%= f.label :branch_office, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :branch_office, class: "form-control" %>
      </div>
    
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/branch_office_addresses/edit.html.erb
<div class="page-header">
  <%= link_to branch_office_addresses_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @branch_office_address, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing branch_office_address</h1>
</div>

<%= render 'form' %>

app/views/branch_office_addresses/index.html.erb
<div class="page-header">
  <%= link_to new_branch_office_address_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Branch office address
  <% end %>
  <h1>Listing branch_office_addresses</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Street name</th>
            <th>Street number</th>
            <th>Monoblock</th>
            <th>Floor</th>
            <th>Department number</th>
            <th>City</th>
            <th>Branch office</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @branch_office_addresses) do |branch_office_address| %>
            <td><%= branch_office_address.street_name %></td>
            <td><%= branch_office_address.street_number %></td>
            <td><%= branch_office_address.monoblock %></td>
            <td><%= branch_office_address.floor %></td>
            <td><%= branch_office_address.department_number %></td>
            <td><%= branch_office_address.city %></td>
            <td><%= branch_office_address.branch_office %></td>
            <td><%= link_to 'Show', branch_office_address %></td>
        <td><%= link_to 'Edit', edit_branch_office_address_path(branch_office_address) %></td>
        <td><%= link_to 'Destroy', branch_office_address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/branch_office_addresses/new.html.erb
<div class="page-header">
  <%= link_to branch_office_addresses_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New branch_office_address</h1>
</div>

<%= render 'form' %>

app/views/branch_office_addresses/show.html.erb
<div class="page-header">
  <%= link_to branch_office_addresses_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_branch_office_address_path(@branch_office_address), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show branch_office_address</h1>
</div>

<dl class="dl-horizontal">
  <dt>Street name:</dt>
  <dd><%= @branch_office_address.street_name %></dd>

  <dt>Street number:</dt>
  <dd><%= @branch_office_address.street_number %></dd>

  <dt>Monoblock:</dt>
  <dd><%= @branch_office_address.monoblock %></dd>

  <dt>Floor:</dt>
  <dd><%= @branch_office_address.floor %></dd>

  <dt>Department number:</dt>
  <dd><%= @branch_office_address.department_number %></dd>

  <dt>City:</dt>
  <dd><%= @branch_office_address.city %></dd>

  <dt>Branch office:</dt>
  <dd><%= @branch_office_address.branch_office %></dd>

</dl>