config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  devise_for :users
  resources :users, :controller => "users"
  resources :branch_office_addresses
  resources :branch_offices
  resources :client_addresses
  resources :clients
  resources :cities
  resources :states
  resources :countries

  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/branch_office.rb
class BranchOffice < ApplicationRecord
  belongs_to :client
  has_many :branch_office_addresses
end

app/models/city.rb
class City < ApplicationRecord
	belongs_to :state
	has_one :client_address
	has_one :branch_office_address
end

app/models/client.rb
class Client < ApplicationRecord
	has_many :client_addresses, :dependent => :destroy
	has_many :branch_offices, :dependent => :destroy


	accepts_nested_attributes_for :client_addresses, :allow_destroy => true


	validates_presence_of :first_name, :last_name, 
		:message => "Este campo es obligatorio."
	validates :dni_number, :cuil_number, 
		numericality: { message: "Se permite solo numeros enteros."}, 
		:allow_nil => true
	#validates_length_of :dni_number, :minimum => 8, :maximum => 8, :message => "Ingrese un DNI válido. (mínimo 8 caracteres numericos, sin puntos ni comas)"
	#validates_length_of :cuil_number, :minimum => 11, :maximum => 11, :message => "Ingrese un CUIL válido. (mínimo 11 caracteres numericos, sin puntos ni comas)"
	validates :email, 
		format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, message: "formato email@email.com"  }, 
		:allow_nil => true

end

app/models/client_address.rb
class ClientAddress < ApplicationRecord
  belongs_to :city
  has_one :state, through: :city
  has_one :country, through: :state
  belongs_to :client

  accepts_nested_attributes_for :city, :state, :country, :allow_destroy => true


end

app/models/country.rb
class Country < ApplicationRecord
	has_many :states
	validates_presence_of :name
end

app/models/state.rb
class State < ApplicationRecord
	belongs_to :country
	has_many :cities
end

app/models/task.rb
class Task < ApplicationRecord
	has_many :user_tasks
	has_many :users, :through => :user_tasks

	#attr_reader :users

	after_create :save_users

	#Custom setter
	def users=(value)
		@users = value
	end

	private

	def save_users
		@users.each do |user_id|
			UserTask.create(user_id: user_id, task_id: self.id)
		end
	end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_tasks
  has_many :tasks, :through => :user_tasks
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :confirmable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :avatar, AvatarUploader
  extend Enumerize
  enumerize :role, in:[:'root', :'admin', :'user'], default: :'user'

end

app/models/user_task.rb
class UserTask < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/controllers/branch_offices_controller.rb
class BranchOfficesController < ApplicationController
  before_action :set_branch_office, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @branch_offices = BranchOffice.all
    respond_with(@branch_offices)
  end

  def show
    respond_with(@branch_office)
  end

  def new
    @branch_office = BranchOffice.new
    respond_with(@branch_office)
  end

  def edit
  end

  def create
    @branch_office = BranchOffice.new(branch_office_params)
    @branch_office.save
    respond_with(@branch_office)
  end

  def update
    @branch_office.update(branch_office_params)
    respond_with(@branch_office)
  end

  def destroy
    @branch_office.destroy
    respond_with(@branch_office)
  end

  private
    def set_branch_office
      @branch_office = BranchOffice.find(params[:id])
    end

    def branch_office_params
      params.require(:branch_office).permit(:name, :cuit_number, :email, :status, :mobile_phone, :home_phone, :other_phone, :client_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @tasks = Task.all
    respond_with(@tasks)
  end

  def show
    respond_with(@task)
  end

  def new
    @task = Task.new
    @users = User.all
    respond_with(@task)
  end

  def edit
  end

  def create
    @task = Task.new(task_params)
    @task.users = params[:users]
    if @task.save
      redirect_to @task
    else
      render :new
    end
    #respond_with(@task)
  end

  def update
    @task.update(task_params)
    respond_with(@task)
  end

  def destroy
    @task.destroy
    respond_with(@task)
  end

  private
    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:title, :description, :users)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
    	@users = User.where.not(id: current_user.id)
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	# def link_to_remove_fields(name, f)
	# 	f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
	# end

	# def link_to_add_fields(name, f, association)
	# 	new_object = f.object.class.reflect_on_association(association).klass.new
	# 	fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
	#   	render(association.to_s.singularize + "_fields", :f => builder)
	# end
	# 	link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
	# end
	# def link_to_add_fields(name, f, association)  
 #  		new_object = f.object.class.reflect_on_association(association).klass.new  
 #  		fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|  
 #    	render(association.to_s.singularize + "_fields", :f => builder)  
 #  	end  
 #  	link_to name, "#", :onclick => h("add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")"), remote: true
	# end  
end

app/helpers/branch_offices_helper.rb
module BranchOfficesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
	def link_to_add_fields(name, f, association)
	    new_object = f.object.send(association).klass.new
	    id = new_object.object_id
	    fields = f.fields_for(association, new_object, child_index: id) do |document|
	      render(association.to_s.singularize + "_fields", f: document)
	    end
	    link_to(name, '', class: "add_fields btn btn-success", data: { id: id, fields: fields.gsub("\n", "")})
	end
	def link_to_remove_fields(name, f)
		f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
	end
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/branch_offices/_form.html.erb
<%= form_for(@branch_office, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @branch_office.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@branch_office.errors.count, "error") %> prohibited this branch_office from being saved:</h4>

      <ul>
      <% @branch_office.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    
      <%= f.label :name, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :name, class: "form-control" %>
      </div>
    
  </div>
  <div class="form-group">
    
      <%= f.label :cuit_number, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.number_field :cuit_number, class: "form-control" %>
      </div>
    
  </div>
  <div class="form-group">
    
      <%= f.label :email, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :email, class: "form-control" %>
      </div>
    
  </div>
  <div class="form-group">
    
      <%= f.label :status, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :status, class: "form-control" %>
      </div>
    
  </div>
  <div class="form-group">
    
      <%= f.label :mobile_phone, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.number_field :mobile_phone, class: "form-control" %>
      </div>
    
  </div>
  <div class="form-group">
    
      <%= f.label :home_phone, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.number_field :home_phone, class: "form-control" %>
      </div>
    
  </div>
  <div class="form-group">
    
      <%= f.label :other_phone, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.number_field :other_phone, class: "form-control" %>
      </div>
    
  </div>
  <div class="form-group">
    
      <%= f.label :client, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :client, class: "form-control" %>
      </div>
    
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/branch_offices/edit.html.erb
<div class="page-header">
  <%= link_to branch_offices_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @branch_office, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing branch_office</h1>
</div>

<%= render 'form' %>

app/views/branch_offices/index.html.erb
<div class="page-header">
  <%= link_to new_branch_office_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Branch office
  <% end %>
  <h1>Listing branch_offices</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>Cuit number</th>
            <th>Email</th>
            <th>Status</th>
            <th>Mobile phone</th>
            <th>Home phone</th>
            <th>Other phone</th>
            <th>Client</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @branch_offices) do |branch_office| %>
            <td><%= branch_office.name %></td>
            <td><%= branch_office.cuit_number %></td>
            <td><%= branch_office.email %></td>
            <td><%= branch_office.status %></td>
            <td><%= branch_office.mobile_phone %></td>
            <td><%= branch_office.home_phone %></td>
            <td><%= branch_office.other_phone %></td>
            <td><%= branch_office.client %></td>
            <td><%= link_to 'Show', branch_office %></td>
        <td><%= link_to 'Edit', edit_branch_office_path(branch_office) %></td>
        <td><%= link_to 'Destroy', branch_office, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/branch_offices/new.html.erb
<div class="page-header">
  <%= link_to branch_offices_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New branch_office</h1>
</div>

<%= render 'form' %>

app/views/branch_offices/show.html.erb
<div class="page-header">
  <%= link_to branch_offices_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_branch_office_path(@branch_office), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show branch_office</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @branch_office.name %></dd>

  <dt>Cuit number:</dt>
  <dd><%= @branch_office.cuit_number %></dd>

  <dt>Email:</dt>
  <dd><%= @branch_office.email %></dd>

  <dt>Status:</dt>
  <dd><%= @branch_office.status %></dd>

  <dt>Mobile phone:</dt>
  <dd><%= @branch_office.mobile_phone %></dd>

  <dt>Home phone:</dt>
  <dd><%= @branch_office.home_phone %></dd>

  <dt>Other phone:</dt>
  <dd><%= @branch_office.other_phone %></dd>

  <dt>Client:</dt>
  <dd><%= @branch_office.client %></dd>

</dl>