config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  devise_for :users
  resources :users, :controller => "users"
  resources :branch_office_addresses
  resources :branch_offices
  resources :client_addresses
  resources :clients
  resources :cities
  resources :states
  resources :countries

  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/branch_office.rb
class BranchOffice < ApplicationRecord
  belongs_to :client
  has_many :branch_office_addresses
end

app/models/branch_office_address.rb
class BranchOfficeAddress < ApplicationRecord
  belongs_to :city
  belongs_to :branch_office
end

app/models/city.rb
class City < ApplicationRecord
	belongs_to :state
	has_one :client_address
	has_one :branch_office_address
end

app/models/client.rb
class Client < ApplicationRecord
	has_many :client_addresses, :dependent => :destroy
	has_many :branch_offices, :dependent => :destroy


	accepts_nested_attributes_for :client_addresses, :allow_destroy => true


	validates_presence_of :first_name, :last_name, 
		:message => "Este campo es obligatorio."
	validates :dni_number, :cuil_number, 
		numericality: { message: "Se permite solo numeros enteros."}, 
		:allow_nil => true
	#validates_length_of :dni_number, :minimum => 8, :maximum => 8, :message => "Ingrese un DNI válido. (mínimo 8 caracteres numericos, sin puntos ni comas)"
	#validates_length_of :cuil_number, :minimum => 11, :maximum => 11, :message => "Ingrese un CUIL válido. (mínimo 11 caracteres numericos, sin puntos ni comas)"
	validates :email, 
		format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, message: "formato email@email.com"  }, 
		:allow_nil => true

end

app/models/client_address.rb
class ClientAddress < ApplicationRecord
  belongs_to :city
  has_one :state, through: :city
  has_one :country, through: :state
  belongs_to :client

  accepts_nested_attributes_for :city, :state, :country, :allow_destroy => true


end

app/models/country.rb
class Country < ApplicationRecord
	has_many :states
	validates_presence_of :name
end

app/models/state.rb
class State < ApplicationRecord
	belongs_to :country
	has_many :cities
end

app/models/task.rb
class Task < ApplicationRecord
	has_many :user_tasks
	has_many :users, :through => :user_tasks

	#attr_reader :users

	after_create :save_users

	#Custom setter
	def users=(value)
		@users = value
	end

	private

	def save_users
		@users.each do |user_id|
			UserTask.create(user_id: user_id, task_id: self.id)
		end
	end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_tasks
  has_many :tasks, :through => :user_tasks
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :confirmable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :avatar, AvatarUploader
  extend Enumerize
  enumerize :role, in:[:'root', :'admin', :'user'], default: :'user'

end

app/models/user_task.rb
class UserTask < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:name, :state_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @tasks = Task.all
    respond_with(@tasks)
  end

  def show
    respond_with(@task)
  end

  def new
    @task = Task.new
    @users = User.all
    respond_with(@task)
  end

  def edit
  end

  def create
    @task = Task.new(task_params)
    @task.users = params[:users]
    if @task.save
      redirect_to @task
    else
      render :new
    end
    #respond_with(@task)
  end

  def update
    @task.update(task_params)
    respond_with(@task)
  end

  def destroy
    @task.destroy
    respond_with(@task)
  end

  private
    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:title, :description, :users)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
    	@users = User.where.not(id: current_user.id)
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	# def link_to_remove_fields(name, f)
	# 	f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
	# end

	# def link_to_add_fields(name, f, association)
	# 	new_object = f.object.class.reflect_on_association(association).klass.new
	# 	fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
	#   	render(association.to_s.singularize + "_fields", :f => builder)
	# end
	# 	link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
	# end
	# def link_to_add_fields(name, f, association)  
 #  		new_object = f.object.class.reflect_on_association(association).klass.new  
 #  		fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|  
 #    	render(association.to_s.singularize + "_fields", :f => builder)  
 #  	end  
 #  	link_to name, "#", :onclick => h("add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")"), remote: true
	# end  
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
	def link_to_add_fields(name, f, association)
	    new_object = f.object.send(association).klass.new
	    id = new_object.object_id
	    fields = f.fields_for(association, new_object, child_index: id) do |document|
	      render(association.to_s.singularize + "_fields", f: document)
	    end
	    link_to(name, '', class: "add_fields btn btn-success", data: { id: id, fields: fields.gsub("\n", "")})
	end
	def link_to_remove_fields(name, f)
		f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
	end
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/_form.html.erb
<%= form_for(city) do |f| %>
  <% if city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% city.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :state_id %>
    <%= f.text_field :state_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<h1>Editing City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>

app/views/cities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cities.each do |city| %>
      <tr>
        <td><%= city.name %></td>
        <td><%= city.state %></td>
        <td><%= link_to 'Show', city %></td>
        <td><%= link_to 'Edit', edit_city_path(city) %></td>
        <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New City', new_city_path %>

app/views/cities/new.html.erb
<h1>New City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Back', cities_path %>

app/views/cities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @city.name %>
</p>

<p>
  <strong>State:</strong>
  <%= @city.state %>
</p>

<%= link_to 'Edit', edit_city_path(@city) %> |
<%= link_to 'Back', cities_path %>

app/views/tasks/_form.html.erb
<%= form_for(@task, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @task.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h4>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="panel panel-default">
    <div class="panel-heading">
      
    </div>
    <div class="panel-body">
        <div class="form-group">
          <div class="input-group">
            <span class="input-group-addon" id="title">* Título</span>
            <%=f.text_field :title, :class => "form-control", :attributes=>"aria-describedby='title'"%>
          </div>
        </div>

        <div class="form-group">
          <div class="input-group">
            <span class="input-group-addon" id="description">Descripción</span>
            <%=f.text_field :description, :class => "form-control", :attributes=>"aria-describedby='description'"%>
          </div>
        </div>

<!--         <div class="form-group">
          <div class="input-group">
            <span class="input-group-addon" id="description">Usuarios Asociados</span>
            <%=f.text_field :description, :class => "form-control", :attributes=>"aria-describedby='description'"%>
          </div>
        </div> -->










    </div>
  </div>











  <div class="form-group">
    <% @users.each do |u| %>
      <div class="field">
        <%= check_box_tag "users[]", u.id %> <%= u.email %>
      </div>
    <%end%>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<div class="page-header">
  <%= link_to tasks_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @task, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing task</h1>
</div>

<%= render 'form' %>

app/views/tasks/index.html.erb
<div class="page-header">
  <%= link_to new_task_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Task
  <% end %>
  <h1>Listing tasks</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Title</th>
            <th>Description</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @tasks) do |task| %>
            <td><%= task.title %></td>
            <td><%= task.description %></td>
            <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tasks/new.html.erb
<div class="page-header">
  <%= link_to tasks_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Atrás
  <% end %>
  <h1>Nueva Tarea</h1>
</div>

<%= render 'form' %>

app/views/tasks/show.html.erb
<div class="page-header">
  <%= link_to tasks_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_task_path(@task), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show task</h1>
</div>

<dl class="dl-horizontal">
  <dt>Título:</dt>
  <dd><%= @task.title %></dd>

  <dt>Descripción:</dt>
  <dd><%= @task.description %></dd>

  <dt>Usuarios Asignados</dt>
  <table>
    <tbody>
      <% @task.users.each do |u| %>
        <tr>  
          <dd><%= u.email %></dd>          
        </tr>
      <%end%>
    </tbody>    
  </table>
</dl>

app/views/users/index.html.erb
<!-- Listado de Usuarios -->
<div class="panel panel-primary">
	<div class="panel-heading">
		<div class="panel-heading clearfix">
            <h4 class="panel-title pull-left" style="padding-top: 7.5px;">Usuarios</h4>
            <div class="input-group">                    
                <div class="input-group-btn">
                	<button class="btn btn-primary pull-right"><i class="fa fa-user-plus"></i></button>
                    <button class="btn btn-primary pull-right"><i class="fa fa-search"></i></button>
                    <input type="text" class="form-control pull-right" placeholder="Buscar" style="max-width: 200px;">                    
                </div>
            </div>
        </div>
	</div>
	<div class="panel-body">
		<table class="display compact nowrap" width="100%" cellspacing="0" id="users">
			<thead class="thead-default">
				<tr>
					<th class="text-xs-center">
						<i class="fa fa-user fa-lg"  aria-hidden="true"></i>
					</th>
					<th class="text-xs-center">Email</th>
					<th>Rol</th>
					<th class="text-xs-center">Estado</th>
				</tr>
			</thead>
			<tbody>
				<% @users.each do |f| %>
					<tr>
						<% if (f.last_name.present? || f.first_name.present?) %>
							<td><%= f.last_name %> <%= f.first_name %></td>
						<%else%>
							<td class="small muted">¡empty!</td>
						<%end%>
						<td><%= f.email %></td>
						<td><%= f.role %></td>
						<td><%= f.status %></td>
					</tr>
				<%end%>
			</tbody>
		</table>		
	</div>
</div>